services:
  postgres:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    env:
      - POSTGRES_DB=tw_deuni
      - POSTGRES_USER=zabavalabs
      - POSTGRES_PASSWORD=z@b@v@commun1ty
    ports:
      - "5432:5432"
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
      restart_policy:
        condition: on-failure

  thirdweb:
    image: thirdweb/engine:latest
    env:
      - POSTGRES_CONNECTION_URL
      - THIRDWEB_API_SECRET_KEY
      - ENCRYPTION_PASSWORD
      - ADMIN_WALLET_ADDRESS
    ports:
      - "3005:3005"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
      restart_policy:
        condition: on-failure
volumes:
  db_data:
